export const SELLER_CREATE_REQUEST = "SELLER_CREATE_REQUEST";
export const SELLER_CREATE_SUCCESS = "SELLER_CREATE_SUCCESS";
export const SELLER_CREATE_FAILURE = "SELLER_CREATE_FAILURE";

export const SELLER_ACCOUNT_REQUEST = "SELLER_ACCOUNT_REQUEST";
export const SELLER_ACCOUNT_SUCCESS = "SELLER_ACCOUNT_SUCCESS";
export const SELLER_ACCOUNT_FAILURE = "SELLER_ACCOUNT_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
